// rules-data.js
// Built-in country rules used as a fallback when api.snapitid.ai is unreachable.
// The runtime always tries the API first; only the in-app shape needs to match.

export const LOCAL_COUNTRY_RULES = {
  US: {
    id: "us_rules",
    countryCode: "US",
    countryName: "United States",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  CA: {
    id: "ca_rules",
    countryCode: "CA",
    countryName: "Canada",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  GB: {
    id: "gb_rules",
    countryCode: "GB",
    countryName: "United Kingdom",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "LIGHT_NEUTRAL",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 2,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  DE: {
    id: "de_rules",
    countryCode: "DE",
    countryName: "Germany",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  FR: {
    id: "fr_rules",
    countryCode: "FR",
    countryName: "France",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: true,
    headCoverageAllowed: false,
    minResolution: 2,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  JP: {
    id: "jp_rules",
    countryCode: "JP",
    countryName: "Japan",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  AU: {
    id: "au_rules",
    countryCode: "AU",
    countryName: "Australia",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  CN: {
    id: "cn_rules",
    countryCode: "CN",
    countryName: "China",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  IT: {
    id: "it_rules",
    countryCode: "IT",
    countryName: "Italy",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  ES: {
    id: "es_rules",
    countryCode: "ES",
    countryName: "Spain",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  NL: {
    id: "nl_rules",
    countryCode: "NL",
    countryName: "Netherlands",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  SE: {
    id: "se_rules",
    countryCode: "SE",
    countryName: "Sweden",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  PL: {
    id: "pl_rules",
    countryCode: "PL",
    countryName: "Poland",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 37, height: 46, headHeight: 294 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  IN: {
    id: "in_rules",
    countryCode: "IN",
    countryName: "India",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  SG: {
    id: "sg_rules",
    countryCode: "SG",
    countryName: "Singapore",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  TH: {
    id: "th_rules",
    countryCode: "TH",
    countryName: "Thailand",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  VN: {
    id: "vn_rules",
    countryCode: "VN",
    countryName: "Vietnam",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  ID: {
    id: "id_rules",
    countryCode: "ID",
    countryName: "Indonesia",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  PH: {
    id: "ph_rules",
    countryCode: "PH",
    countryName: "Philippines",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
  MY: {
    id: "my_rules",
    countryCode: "MY",
    countryName: "Malaysia",
    passportSize: { width: 35, height: 45, headHeight: 288 },
    visaSize: { width: 35, height: 45, headHeight: 288 },
    backgroundColorRequirement: "WHITE",
    smileAllowed: false,
    glassesAllowed: false,
    headCoverageAllowed: false,
    minResolution: 3,
    printFormat: "4x6",
    lastUpdated: "local-fallback",
  },
};
